/* ============================================================
   L'Arte della Guerra — i passaggi
   ------------------------------------------------------------
   Novantasette passaggi tratti da "L'arte della guerra" di Sun
   Tzu (VI-V secolo a.C.), nella tradizione italiana corrente.

   Una precisazione dovuta: il testo di Sun Tzu ci arriva
   attraverso duemilacinquecento anni di traduzioni e riletture,
   e molte formulazioni che circolano oggi sono sintesi o
   parafrasi piuttosto che traduzioni letterali. Questa raccolta
   le tratta per quello che sono: massime di strategia nella
   tradizione di Sun Tzu, non un'edizione critica.

   Il tema serve al filtro. Per aggiungere un passaggio basta
   una riga qui: la pagina non va toccata.
   ============================================================ */

window.CITAZIONI_SUNTZU = [

  /* ---------- Strategia ---------- */
  { testo: 'Le tattiche senza strategia sono il rumore che precede la sconfitta.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'La guerra è di vitale importanza per lo Stato, è la base della vita e della morte, la via per la sopravvivenza o la rovina. È imperativo studiarla a fondo.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Non c\'è esempio di una nazione che abbia tratto beneficio da una guerra prolungata.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Non muoverti se non vedi un vantaggio, non usare il tuo esercito se non hai qualcosa da guadagnare, non combattere se non sei in pericolo critico.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Coloro che sono esperti nel condurre una guerra inducono il nemico ad avanzare di sua iniziativa, attirandolo con qualche vantaggio.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'La base della difesa è non essere attaccabile; la base dell\'attacco è non sbagliare a colpire.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Sii estremamente sottile, anche fino al punto di non avere forma. Sii estremamente misterioso, anche fino al punto di non avere suono. In questo modo puoi essere il padrone del destino del tuo avversario.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Quando l\'armata nemica è in ritirata, non bloccare il suo percorso.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Chi non ha obiettivi a lungo termine incontrerà problemi a breve termine.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Non combattere in modo impulsivo o per rabbia personale; agisci solo quando l\'opportunità è massima.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'La vera abilità consiste nel vincere senza che il nemico se ne accorga.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Tratta bene i prigionieri e usali per i tuoi scopi.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Mostrati debole quando sei forte e forte quando sei debole.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Quando il nemico è unito, separalo.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Se il nemico è collerico, irritalo. Se è arrogante, alimenta la sua vanità.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Chi è prudente e attende il nemico imprudente sarà vittorioso.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Chi conosce quando può combattere e quando non può, sarà vittorioso.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'La guerra è come il fuoco: chi non lo spegne si consumerà da solo.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Nel mezzo del caos, trova la calma.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Quando il nemico apre una porta, devi entrarci.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Non fare affidamento sulle probabilità del nemico di non attaccare: conta sulla tua capacità di renderlo impossibile.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'La prudenza porta alla sicurezza, la precipitazione al pericolo.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Quando non puoi essere forte, ma non puoi essere debole, ritirati strategicamente.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Le opportunità si moltiplicano man mano che vengono colte.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Se il nemico è riposato, disturbalo; se è ben nutrito, affamalo; se è tranquillo, agitalo.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Un piccolo vantaggio può condurre a una grande vittoria se colto al momento giusto.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'La strategia senza tattica è la via più lenta verso la vittoria. La tattica senza strategia è il rumore prima della sconfitta.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Se il nemico ti offre un patto, valuta sempre cosa teme.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Le battaglie si vincono prima di combatterle.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Non provocare il nemico quando è disperato: combattendo disperato diventa più forte.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },
  { testo: 'Le battaglie decisive non sono sempre combattute con le armi.',
    autore: 'Sun Tzu', tema: 'Strategia', fonte: 'L\'arte della guerra' },

  /* ---------- Vittoria senza combattere ---------- */
  { testo: 'Il supremo eccellere non consiste nel vincere ogni battaglia, ma nel sottomettere il nemico senza combattere.',
    autore: 'Sun Tzu', tema: 'Vittoria senza combattere', fonte: 'L\'arte della guerra' },
  { testo: 'La miglior politica è quella di prendere un paese intatto; rovinarlo è inferiore.',
    autore: 'Sun Tzu', tema: 'Vittoria senza combattere', fonte: 'L\'arte della guerra' },
  { testo: 'La vittoria completa si ottiene quando le forze nemiche vengono sottomesse senza spargimento di sangue.',
    autore: 'Sun Tzu', tema: 'Vittoria senza combattere', fonte: 'L\'arte della guerra' },
  { testo: 'Si può essere vinti senza essere sconfitti.',
    autore: 'Sun Tzu', tema: 'Vittoria senza combattere', fonte: 'L\'arte della guerra' },
  { testo: 'Se non puoi vincere, almeno non essere sconfitto.',
    autore: 'Sun Tzu', tema: 'Vittoria senza combattere', fonte: 'L\'arte della guerra' },

  /* ---------- Inganno ---------- */
  { testo: 'Tutta la guerra è basata sull\'inganno.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Chi è abile nel muovere il nemico lo fa apparendo in luoghi che l\'avversario dovrà accorrere. Egli attira il nemico con qualcosa che il nemico deve prendere.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Non c\'è campo di battaglia che non sia un campo di inganni.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Il generale che non conosce l\'inganno non può ottenere la vittoria.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Quando sei in grado, fingi di non esserlo; quando sei vicino, fingi di essere lontano; quando sei lontano, fingi di essere vicino.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Non inseguire i nemici che si fingono in fuga.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Fai in modo che il nemico creda ciò che vuoi che creda.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Non prendere ciò che è dato gratuitamente dal nemico: potrebbe essere una trappola.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Una trappola efficace richiede che il nemico creda di avere un vantaggio.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },
  { testo: 'Un generale deve saper riconoscere le false apparenze.',
    autore: 'Sun Tzu', tema: 'Inganno', fonte: 'L\'arte della guerra' },

  /* ---------- Conoscenza ---------- */
  { testo: 'Conosci il nemico e conosci te stesso; in cento battaglie non sarai mai in pericolo.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Non attaccare il nemico su terreno difficile o quando non puoi prevedere le sue intenzioni.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Il guerriero intelligente impone la sua volontà al nemico, ma non permette che la volontà del nemico sia imposta su di lui.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Coloro che sono abili nel combattimento non sono noti per la loro intelligenza né per il loro coraggio, ma per la loro abilità nel cogliere il momento favorevole.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Un comandante intelligente evita l\'esercito nemico quando la sua forza è integra e lo colpisce quando è disorganizzato.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Chi è rapido nel comprendere una situazione e decide con risolutezza avrà la meglio.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Non permettere mai al nemico di conoscere le tue vere risorse.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },
  { testo: 'Il segreto della guerra è prevedere ciò che il nemico ritiene imprevedibile.',
    autore: 'Sun Tzu', tema: 'Conoscenza', fonte: 'L\'arte della guerra' },

  /* ---------- Comando ---------- */
  { testo: 'L\'arte di schierare le truppe consiste nel disperderle e concentrarle a seconda della situazione.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Il generale che avanza senza desiderio di gloria e si ritira solo per evitare la punizione, il cui unico pensiero è proteggere il suo paese, è il gioiello del regno.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Un buon generale non è impulsivo e non si compiace del proprio valore.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Quando le truppe sono affamate, i generali sono responsabili della loro morte.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Il generale che ascolta troppi consiglieri non prenderà mai decisioni efficaci.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Quando le truppe non hanno obiettivi comuni, la colpa è del comandante.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Quando il generale è debole, anche il soldato più forte combatterà senza convinzione.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Un generale deve avere tre qualità: prudenza, sincerità e fermezza.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Il buon comandante usa le circostanze, non ne è usato.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'La fermezza di un generale determina il destino di un\'intera nazione.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Quando le truppe sono spaventate, non avanzare; quando sono motivate, non trattenerle.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Il comandante che agisce per rabbia perderà sempre la propria lucidità.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Il comandante saggio considera ogni vantaggio e ogni pericolo.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'La forza di un esercito dipende dall’armonia tra comandante e truppe.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Tratta i tuoi soldati come figli, e ti seguiranno in valloni più profondi.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },
  { testo: 'Un generale deve essere imperturbabile: se è nervoso, lo saranno anche i suoi uomini.',
    autore: 'Sun Tzu', tema: 'Comando', fonte: 'L\'arte della guerra' },

  /* ---------- Disciplina ---------- */
  { testo: 'Il disordine nasce dall\'ordine, la codardia dal coraggio, la debolezza dalla forza.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'La disciplina è data da un\'applicazione chiara e rigorosa dei regolamenti, anche in situazioni difficili.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Se le truppe sono unite come un solo uomo, il coraggio del più vile non sarà inferiore a quello del più valoroso.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Un esercito che manca di disciplina è destinato alla sconfitta.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Se il sovrano impartisce ordini confusi, il generale e le truppe ne subiranno le conseguenze.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Un buon comandante ottiene obbedienza senza gridare e rispetto senza punire.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Gli eserciti vincono grazie alla coordinazione e perdono per mancanza di disciplina.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Un esercito che si muove come un solo uomo è invincibile.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'La chiarezza nei comandi evita il caos nei ranghi.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },
  { testo: 'Premia i soldati per stimolare lo spirito, puniscili per mantenere l\'ordine.',
    autore: 'Sun Tzu', tema: 'Disciplina', fonte: 'L\'arte della guerra' },

  /* ---------- Preparazione ---------- */
  { testo: 'Pianifica per ciò che è difficile mentre è ancora facile, fai ciò che è grande mentre è ancora piccolo.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'La manovra è vantaggiosa; ma pericolosa è la manovra non pianificata.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'Un esercito senza sufficiente approvvigionamento è destinato alla sconfitta.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'Colpisci il nemico dove non è preparato, appari dove non ti aspetta.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'La guerra richiede spese: non prolungarla inutilmente.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'Non contare mai sul fatto che il nemico non arrivi; conta sul fatto che tu sarai pronto quando arriverà.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'Alla fine, la vittoria appartiene a chi la prepara meglio.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'Il nemico che appare immobile sta preparando una grande mossa.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },
  { testo: 'Non affidarti alla fortuna, affidati alla preparazione.',
    autore: 'Sun Tzu', tema: 'Preparazione', fonte: 'L\'arte della guerra' },

  /* ---------- Rapidità ---------- */
  { testo: 'La fretta ti farà fallire.',
    autore: 'Sun Tzu', tema: 'Rapidità', fonte: 'L\'arte della guerra' },
  { testo: 'Se i tuoi piani sono oscuri e impenetrabili come la notte, quando ti muovi, cadi come un fulmine.',
    autore: 'Sun Tzu', tema: 'Rapidità', fonte: 'L\'arte della guerra' },
  { testo: 'Chi è rapido nel provocare il nemico è pronto alla vittoria.',
    autore: 'Sun Tzu', tema: 'Rapidità', fonte: 'L\'arte della guerra' },
  { testo: 'La velocità è l’essenza della guerra.',
    autore: 'Sun Tzu', tema: 'Rapidità', fonte: 'L\'arte della guerra' },
  { testo: 'Quando il nemico non è pronto, colpisci in modo fulmineo.',
    autore: 'Sun Tzu', tema: 'Rapidità', fonte: 'L\'arte della guerra' },

  /* ---------- Terreno ---------- */
  { testo: 'La forza di un esercito è come il masso che viene fatto rotolare: la sua energia si basa sul terreno su cui si muove e sull\'impulso che gli viene dato.',
    autore: 'Sun Tzu', tema: 'Terreno', fonte: 'L\'arte della guerra' },
  { testo: 'L\'acqua modella il suo corso in base al terreno; l\'esercito vince in base alla situazione del nemico.',
    autore: 'Sun Tzu', tema: 'Terreno', fonte: 'L\'arte della guerra' },
  { testo: 'Il terreno è il tuo migliore alleato o il tuo peggior nemico.',
    autore: 'Sun Tzu', tema: 'Terreno', fonte: 'L\'arte della guerra' }
];
